### ISSUE TITLE
조건식 오류

### ISSUE THREAD

**Issue by ungmo2** [gayoungaa91/T.I.L-FDS12#1]
https://github.com/gayoungaa91/T.I.L-FDS12/blob/c853a18eaba6d4736dfc306af7b97520d807ed16/homework/exercise.js#L9

조건식 10 < x < 20을 평가하면 10 < x 이 먼저 평가되고 그 결과값(true or false)과 < 20이 평가됩니다.
따라서 위 조건식은 언제나 true입니다. x > 10 && x < 20으로 해주어야 정상 동작합니다.

**Comment by gayoungaa91** [comment]
네 확인했습니당 
감사합니다 :)
