### ISSUE TITLE
var와 let 혼용

### ISSUE THREAD

**Issue by ungmo2** [gayoungaa91/T.I.L-FDS12#3]
https://github.com/gayoungaa91/T.I.L-FDS12/blob/c853a18eaba6d4736dfc306af7b97520d807ed16/homework/exercise.js#L20

var와 let 혼용은 좋지 않습니다

**Comment by gayoungaa91** [comment]
넹 혼용해서 사용하지 않겠습니다.
피드백 감사드려요 :)
